/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author olive
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ola = new javax.swing.JLabel();
        iconOla = new javax.swing.JLabel();
        iconProjetor = new javax.swing.JLabel();
        filmePanel = new javax.swing.JPanel();
        iconSerie = new javax.swing.JLabel();
        seriejButton = new javax.swing.JButton();
        seriePanel = new javax.swing.JPanel();
        filmeIcon = new javax.swing.JLabel();
        filmejButton = new javax.swing.JButton();
        favoritosPanel = new javax.swing.JPanel();
        favoritosIcon = new javax.swing.JLabel();
        favoritosjButton = new javax.swing.JButton();
        playlistPanel = new javax.swing.JPanel();
        playlistIcon = new javax.swing.JLabel();
        playlistjButton = new javax.swing.JButton();
        estatisticasPanel = new javax.swing.JPanel();
        estatisticaIcon = new javax.swing.JLabel();
        estatisticajButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AvaliaFlix");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagensProj/clapperboard.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ola.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        ola.setForeground(new java.awt.Color(64, 123, 255));
        ola.setText("Olá, usuário!");

        iconOla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensProj/hello.png"))); // NOI18N

        iconProjetor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensProj/projector.png"))); // NOI18N

        filmePanel.setBackground(new java.awt.Color(255, 255, 255));
        filmePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(64, 123, 255)));

        iconSerie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensProj/serie.png"))); // NOI18N

        seriejButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        seriejButton.setForeground(new java.awt.Color(64, 123, 255));
        seriejButton.setText("Série");
        seriejButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seriejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seriejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filmePanelLayout = new javax.swing.GroupLayout(filmePanel);
        filmePanel.setLayout(filmePanelLayout);
        filmePanelLayout.setHorizontalGroup(
            filmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filmePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(filmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconSerie)
                    .addComponent(seriejButton))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        filmePanelLayout.setVerticalGroup(
            filmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filmePanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(iconSerie)
                .addGap(27, 27, 27)
                .addComponent(seriejButton)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        seriePanel.setBackground(new java.awt.Color(255, 255, 255));
        seriePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(64, 123, 255)));

        filmeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensProj/filme.png"))); // NOI18N

        filmejButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        filmejButton.setForeground(new java.awt.Color(64, 123, 255));
        filmejButton.setText("Filme");
        filmejButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filmejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seriePanelLayout = new javax.swing.GroupLayout(seriePanel);
        seriePanel.setLayout(seriePanelLayout);
        seriePanelLayout.setHorizontalGroup(
            seriePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seriePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(seriePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filmeIcon)
                    .addComponent(filmejButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        seriePanelLayout.setVerticalGroup(
            seriePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seriePanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(filmeIcon)
                .addGap(28, 28, 28)
                .addComponent(filmejButton)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        favoritosPanel.setBackground(new java.awt.Color(255, 255, 255));
        favoritosPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(64, 123, 255)));

        favoritosIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensProj/favorite.png"))); // NOI18N

        favoritosjButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        favoritosjButton.setForeground(new java.awt.Color(64, 123, 255));
        favoritosjButton.setText("Favoritos");
        favoritosjButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        favoritosjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favoritosjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout favoritosPanelLayout = new javax.swing.GroupLayout(favoritosPanel);
        favoritosPanel.setLayout(favoritosPanelLayout);
        favoritosPanelLayout.setHorizontalGroup(
            favoritosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, favoritosPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(favoritosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(favoritosjButton)
                    .addComponent(favoritosIcon))
                .addGap(28, 28, 28))
        );
        favoritosPanelLayout.setVerticalGroup(
            favoritosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(favoritosPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(favoritosIcon)
                .addGap(26, 26, 26)
                .addComponent(favoritosjButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        playlistPanel.setBackground(new java.awt.Color(255, 255, 255));
        playlistPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(64, 123, 255)));

        playlistIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensProj/playlist.png"))); // NOI18N

        playlistjButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        playlistjButton.setForeground(new java.awt.Color(64, 123, 255));
        playlistjButton.setText("Playlist");
        playlistjButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playlistjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playlistjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout playlistPanelLayout = new javax.swing.GroupLayout(playlistPanel);
        playlistPanel.setLayout(playlistPanelLayout);
        playlistPanelLayout.setHorizontalGroup(
            playlistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playlistPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(playlistjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playlistPanelLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(playlistIcon)
                .addGap(21, 21, 21))
        );
        playlistPanelLayout.setVerticalGroup(
            playlistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playlistPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(playlistIcon)
                .addGap(18, 18, 18)
                .addComponent(playlistjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        estatisticasPanel.setBackground(new java.awt.Color(255, 255, 255));
        estatisticasPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(64, 123, 255)));

        estatisticaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensProj/statistics.png"))); // NOI18N

        estatisticajButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        estatisticajButton.setForeground(new java.awt.Color(64, 123, 255));
        estatisticajButton.setText("Estatítiscas");
        estatisticajButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        estatisticajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estatisticajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout estatisticasPanelLayout = new javax.swing.GroupLayout(estatisticasPanel);
        estatisticasPanel.setLayout(estatisticasPanelLayout);
        estatisticasPanelLayout.setHorizontalGroup(
            estatisticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estatisticasPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(estatisticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estatisticajButton)
                    .addGroup(estatisticasPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(estatisticaIcon)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        estatisticasPanelLayout.setVerticalGroup(
            estatisticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estatisticasPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(estatisticaIcon)
                .addGap(26, 26, 26)
                .addComponent(estatisticajButton)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(iconOla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ola)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(favoritosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seriePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(playlistPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(estatisticasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(filmePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(iconProjetor)
                                .addGap(34, 34, 34))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconOla)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ola)
                        .addGap(9, 9, 9)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filmePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seriePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(iconProjetor)))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estatisticasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(playlistPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(favoritosPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jMenu1.setText("Usuário");

        jMenuItem1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(64, 123, 255));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensProj/trocarUserr.png"))); // NOI18N
        jMenuItem1.setText("Alterar dados do Usuário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void seriejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seriejButtonActionPerformed
        // TODO add your handling code here:
        Séries obj = new Séries();
        obj.setVisible(true);
    }//GEN-LAST:event_seriejButtonActionPerformed

    private void filmejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmejButtonActionPerformed
        // TODO add your handling code here:
        Filmes obj = new Filmes();
        obj.setVisible(true);
    }//GEN-LAST:event_filmejButtonActionPerformed

    private void favoritosjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favoritosjButtonActionPerformed
        // TODO add your handling code here:
        //Favoritos obj1 = new Favoritos();
        //obj1.setVisible(true);

    }//GEN-LAST:event_favoritosjButtonActionPerformed

    private void playlistjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playlistjButtonActionPerformed
        // TODO add your handling code here:
        //Playlist obj = new Playlist();
        //obj.setVisible(true);
    }//GEN-LAST:event_playlistjButtonActionPerformed

    private void estatisticajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estatisticajButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estatisticajButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new AlterarDadosUsuario().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel estatisticaIcon;
    private javax.swing.JButton estatisticajButton;
    private javax.swing.JPanel estatisticasPanel;
    private javax.swing.JLabel favoritosIcon;
    private javax.swing.JPanel favoritosPanel;
    private javax.swing.JButton favoritosjButton;
    private javax.swing.JLabel filmeIcon;
    private javax.swing.JPanel filmePanel;
    private javax.swing.JButton filmejButton;
    private javax.swing.JLabel iconOla;
    private javax.swing.JLabel iconProjetor;
    private javax.swing.JLabel iconSerie;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ola;
    private javax.swing.JLabel playlistIcon;
    private javax.swing.JPanel playlistPanel;
    private javax.swing.JButton playlistjButton;
    private javax.swing.JPanel seriePanel;
    private javax.swing.JButton seriejButton;
    // End of variables declaration//GEN-END:variables
}
